import Link from 'next/link';
import { authFlow } from '@/lib/firebase';

export default function LoginPage() {
  return <main className="min-h-screen px-5 py-8"><section className="mx-auto grid max-w-6xl gap-6 lg:grid-cols-[.9fr_1.1fr]">
    <aside className="rounded-[2.5rem] bg-[var(--navy)] p-8 text-white shadow-2xl shadow-slate-900/20"><Link href="/" className="flex items-center gap-3"><span className="brand-mark size-11 rounded-2xl bg-white/10" /><span className="brand-word text-2xl font-black">SurePay</span></Link><p className="mt-14 text-sm font-black uppercase tracking-[.28em] text-blue-200">Secure access</p><h1 className="brand-word mt-5 text-5xl font-black tracking-[-.06em]">Welcome back to your verification workspace.</h1><div className="mt-8 space-y-3">{authFlow.login.map((step, i) => <p key={step} className="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-blue-50"><b className="text-sky-300">0{i+1}</b> {step}</p>)}</div></aside>
    <form className="rounded-[2.5rem] border border-slate-200 bg-white p-8 shadow-sm"><p className="text-sm font-black uppercase tracking-[.28em] text-[var(--primary)]">Sign in</p><h2 className="brand-word mt-4 text-4xl font-black tracking-[-.05em]">Access your dashboard.</h2><label className="mt-8 block text-sm font-black">Phone number<input className="input-shell mt-2 w-full" inputMode="tel" placeholder="+251 9•• ••• •••" /></label><label className="mt-4 block text-sm font-black">Password<input className="input-shell mt-2 w-full" type="password" placeholder="••••••••" /></label><div className="mt-5 rounded-3xl bg-slate-50 p-5"><p className="font-black">One-time code</p><p className="mt-1 text-sm leading-6 text-[var(--muted)]">Enter the code sent to the phone number on your account.</p><input className="input-shell mt-3 w-full" inputMode="numeric" placeholder="6-digit code" /></div><Link href="/dashboard" className="mt-6 flex justify-center rounded-full blue-gradient px-6 py-4 font-black text-white">Continue</Link><Link href="/create-account" className="mt-4 flex justify-center rounded-full border border-slate-200 px-6 py-4 font-black">Create business account</Link></form>
  </section></main>;
}
